name: Automated Deploy
run-name: "${{ github.workflow }} - development"
on:
  push:
    branches: [ main ]
jobs:  
  deployToS3:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    environment: 
      name: development
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        role-to-assume: '${{ secrets.AWS_ROLE_TO_ASSUME }}'
        role-duration-seconds: 1200
        aws-region: us-east-1
    - name: Add NPM Token
      run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NpmAuthToken }}" > .npmrc'
    - name: Add NPM Token
      run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NpmAuthToken }}" > .npmrc'
    - name: Branch name
      run: echo running on branch $(echo $GITHUB_REF | cut -d"/" -f 4)
    - name: Add Version Number
      run: 'echo "{ \"version\" : \"$(echo $GITHUB_REF | cut -d"/" -f 4)\" }" > ./src/version.json'
    - name: Install Dependencies
      run: |
        yarn install
    - name: Build App
      run: |
        yarn build
    - name: Copy files to the dev account with the AWS CLI
      run: |
        aws s3 sync --delete --acl public-read ./build s3://"${{ secrets.AWS_S3_BUCKET_NAME }}"
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      env:
        SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
      with:
        payload: |
          {
            "environment": "development",
            "message": "Continuous Integration of the main branch finished",
            "status": "${{ job.status }}"
          }

  slackNotification:
    runs-on: ubuntu-latest
    environment: 
      name: development
    steps:
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      env:
        SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
      with:
        payload: |
          {
            "environment": "development",
            "message": "Continuous integration of the main branch began",
            "status": "In Progress"
          }
  
  
