name: CI - Lint App
run-name: "${{ github.workflow }} - ${{ github.ref_name }}"
on: 
  push:
    branches: [ main, release/*/main, release/*/feature/*, release/*/bug/* ]
jobs:
  lintApp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Node Version
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Add NPM Token
      run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NpmAuthToken }}" > .npmrc'
    - name: Install modules
      run: yarn
    - name: Lint project
      run: yarn lint
